# -*- coding: utf-8 -*-
"""svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEbptglNtshfOWXlFjC0r6CQU8Qbta28
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

path = "/content/drive/Shareddrives/CMPE 132_Nerd Squad/MSCAD.csv"
df = pd.read_csv(path)
print(df.shape)
print(df.head())

# Check unique values in Label column
print(df["Label"].unique())  # Make sure the column contains expected values

# Filter the dataset
df_filtered = df[df["Label"].isin(["HTTP_DDoS", "Normal"])]

# Confirm the filtering
print(df_filtered["Label"].value_counts())  # Verify class distribution
print(df_filtered.shape)  # Check number of remaining rows

from sklearn.preprocessing import StandardScaler

# Convert all applicable columns to numeric (ignoring errors)
df_filtered = df_filtered.apply(pd.to_numeric, errors='ignore')

# Select only numeric columns (excluding the Label column)
numeric_cols = df_filtered.select_dtypes(include=['float64', 'int64']).columns
print(numeric_cols)  # Check which columns are selected

# Normalize the numeric features
scaler = StandardScaler()
df_filtered[numeric_cols] = scaler.fit_transform(df_filtered[numeric_cols])

# Check the transformed dataset
print(df_filtered.head())

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

# Separate features and target variable
X = df_filtered[numeric_cols]  # Features
y = df_filtered["Label"]  # Labels

# Encode labels as numbers (Normal -> 0, HTTP DDoS -> 1)
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Confirm dataset shapes
print("Training set:", X_train.shape, y_train.shape)
print("Test set:", X_test.shape, y_test.shape)

from sklearn.svm import SVC

# Create the SVM model
svm_model = SVC(kernel='rbf', C=1.0, gamma='scale')  # RBF is the default kernel

# Train the model
svm_model.fit(X_train, y_train)

# Make predictions
svm_preds = svm_model.predict(X_test)

# Evaluate
print("SVM Results:")
print("Accuracy:", accuracy_score(y_test, svm_preds))
print(classification_report(y_test, svm_preds, target_names=label_encoder.classes_))